### ISSUE TITLE
Usage of a more accurate distance Caclulation

### ISSUE THREAD

**Issue by henningvs** [AndriiHeonia/hull#1]
I wanted to use your library for a project where I would like to create a hull for a number of geopositions. 
To make the calculation more accurate I would to build an (optional) method as an alternative for _sqLength() to calcute the distance by Haversine (http://en.wikipedia.org/wiki/Haversine_formula) and not by Pythagoras.

Thank you for this great project by the way!

**Comment by AndriiHeonia** [comment]
@Haves1001 hmm, I think you are right and it can be useful... But before implementing this feature I would like to see concave hull on any 3D map and compare how it looks with Pythagoras formula and how it looks with Haversine formula.

Have you already tried to replace _sqLength() function by Haversine formula? If yes, can you show me    example with results?

**Comment by Haves1001** [comment]
I will try to replace it the next the few days. This shouldn't be too hard, as I  already wrote the necessary javascript for this. And I will also try to make a (good) example for which kind of hulls this could be useful.

What I would to achieve with this, is to solve the problem that maxEdgeLen at the moment is defined in degree for any geo-location using lat and long. And I think it would be more useful to use the distance in meter as maxEdgeLen, as the distance (in meters) given by the degree-value differs from the location on the globe.

**Comment by Haves1001** [comment]
![10 1degree](https://cloud.githubusercontent.com/assets/5406293/6098815/f3cb79c4-afe9-11e4-8531-36ae14f6eb50.PNG) ![10degree](https://cloud.githubusercontent.com/assets/5406293/6098814/f3ca1660-afe9-11e4-9bdc-748114653f6d.PNG) ![1kmeter](https://cloud.githubusercontent.com/assets/5406293/6098822/0c16710a-afea-11e4-8cf4-1521579606ea.PNG) 
1. 10.1 Degree limit
2. 10 Degree limit
3. 1 Kilometer limit

As you can see in picture 1 and 2 the markers are at a distance of 10 degrees. So if I choose a slightly higher degree (10.1° in the second picture) none of the lines are being spliced. And if I choose 10° or lower every connection will be sliced.
I hope to achieve something like in the 3rd picture, as the distance between the markers is higly unequal despite of the equal degree distance.

I will upload a pull request so we can maybe work with the same example. At the moment I'm working on the following code, as it is using the degree value and not the distance in meter:
            bBoxAround = grid.addBorder2Bbox(bBoxAround, border);
            bBoxSize = bBoxAround[2] - bBoxAround[0];
            midPoint = _midPoint(edge, grid.rangePoints(bBoxAround), convex);           
Maybe you can look into this?

**Comment by Haves1001** [comment]
By the way, how is it possible to autobild the /dist/hull.js file? I didn't find a way to do this and did it manually for the pull request.

**Comment by AndriiHeonia** [comment]
Hello @Haves1001,

I thought about hull.js usage with maps and you're right that it is not the best idea to use Longitudes and Latitudes for the calculation (because they are angles, not points in cartesian coordinate system) and we will have results like this: http://jsbin.com/vocixuzabo/1/

But why we can't project our geo points to the points in cartesian coordinate system (any modern maps library supports this operation) and then calculate concave hull? In this case we will have result like this: http://jsbin.com/tavixazixi/1/

Maybe all geographical calculations/conversations should be in responsibility of GIS systems, not in responsibility of hull.js? What do you think?

PS: you can run `npm test` to build `/dist/hull.js` and run tests.

**Comment by Haves1001** [comment]
This is something I didn't think about and it might be a good approach for the problem. Maybe a much easier solution like the one I pushed would be also possible. Because I always experienced problems by selecting the "right" value for the maxEdgeLength-Value (in Degree). It might be easier for the user to provide a small method to calculate maxEdgeLength in Degree by a given Meter value. If you are interested I could make a proposal for this?

I will do some math regarding haversine vs. pythagoras and will post it the next few days.

**Comment by Haves1001** [comment]
Also what I recognized by this example i made here http://jsbin.com/harofu/2/ is that it's still splicing the lines by the angle and not by the distance like it would make sense. 
Like it is visible in the example the lines are flexing from bottom to top and not otherwise like it should be, as the distance from top to the middle markers is 30°, but the distance from the bottom to the middle marker is 50°. And for both the distance in meter is equivalent to the angle.

**Comment by AndriiHeonia** [comment]
Hello @henningvs,

I'm sorry for the delay with answer. Thank you very much for your pull-request, but I decided to create an example with usage on global map: http://andriiheonia.github.io/hull/#ex5 and leave converting operations for the maps libraries. I think it's not the best idea to hardcode haversine formula inside hull.js. Described in this issue problem can be solved via data preprocessing (converting from LatLngs to XY).

Maybe in future (if I'll see another use cases when custom function for the distance calculation can be useful) I'll back to this question and add parameter `distFn`, but now I don't see use cases when it can be useful.
