### ISSUE TITLE
Hull when multiple outline points are on the same Y axis

### ISSUE THREAD

**Issue by KevinBLT** [AndriiHeonia/hull#11]
Hi there, 

I hope this is still maintained somehow. 
How does the algorithm handle this Shape:

var test = [
      new Point(0,0),
      new Point(100,0),
      new Point(100,200),
      new Point(100,300),
      new Point(100,400),
      new Point(0,400),
    //  new Point(0,300),
    //  new Point(0,200)
    ]

This will produce a shape where the points on the right side are used twice.
If you uncomment the the other two points it's correct. 
I am using this library in a project to get contours from 3D objects. 
So far it seems like I have to get min and max X points and remove points on Y axis between minY and maxY on left and right Y axis border. 

Is there a way to handle that initially?

Best regards

Kevin

**Comment by AndriiHeonia** [comment]
Hello Kevin,

Let's say that you use `concavity = 200`. In this case, algorithm takes edge `[[0, 0], [0, 400]]`, measures its length (length = 400), checks that `length > concavity` and trying to flex it inward. The 1st nearest point is `[100, 300]`, that's why it splits the edge into 2 lines `[[0, 0], [100, 300]]` and `[[0, 400], [100, 300]]`:
<img width="161" alt="screen shot 2018-09-22 at 11 25 53" src="https://user-images.githubusercontent.com/773648/45915726-4cd28800-be5a-11e8-9172-9248dcc5a5b1.png">

After that, it checks 2 newly created edges, the length of [[0, 400], [100, 300]] equals to 141.4213562373095, it's less than 200 so we don't touch it. The length of `[[0, 0], [100, 300]]` equals to 316.22776601683796, it's more than 200 that's why we flex it inward in the same way as it did with `[[0, 0], [0, 400]]`:
<img width="150" alt="screen shot 2018-09-22 at 11 58 39" src="https://user-images.githubusercontent.com/773648/45915996-e13ee980-be5e-11e8-91c9-fb092d1c47b1.png">

That's how it works.

About 3D objects, I don't quite get how you are going to use hull.js for your task. This library works only for 2D objects.

**Comment by AndriiHeonia** [comment]
I'm not sure about this, I assume that double usage might be useful for some shapes, for example, for the shape of an hourglass. For now, I will not change anything because I need to see more real-world examples in which the algorithm doesn't fulfil users expectations. If anyone else will complain then, probably, I will reconsider it.
